name: Release Conda Package

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  conda-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.11'
        conda-build-version: '*'
        anaconda-client: true
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create conda recipe
      run: |
        mkdir -p conda-recipe
        cat > conda-recipe/meta.yaml << EOF
        {% set name = "sec-edgar-toolkit" %}
        {% set version = "${{ steps.get_version.outputs.VERSION }}" %}
        
        package:
          name: {{ name|lower }}
          version: {{ version }}
        
        source:
          url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
          sha256: # This will be filled automatically by conda-build
        
        build:
          noarch: python
          script: pip install . -vv
          number: 0
        
        requirements:
          host:
            - python >=3.8
            - pip
            - setuptools
            - wheel
          run:
            - python >=3.8
            - requests >=2.31.0
            - beautifulsoup4 >=4.12.0
            - lxml >=4.9.0
            - pandas >=2.0.0
        
        test:
          imports:
            - sec_edgar_toolkit
          commands:
            - pip check
          requires:
            - pip
        
        about:
          home: https://github.com/stefanoamorelli/sec-edgar-toolkit
          license: GPL-3.0
          license_family: GPL
          license_file: LICENSE
          summary: Open source toolkit to facilitate working with the SEC EDGAR database
          description: |
            A Python toolkit for working with SEC EDGAR filing data.
            Provides tools to search, retrieve, and parse SEC filings like 10-K, 10-Q, and 8-K forms.
          doc_url: https://github.com/stefanoamorelli/sec-edgar-toolkit#readme
          dev_url: https://github.com/stefanoamorelli/sec-edgar-toolkit
        
        extra:
          recipe-maintainers:
            - stefanoamorelli
        EOF
    
    - name: Build conda package
      shell: bash -l {0}
      run: |
        conda build conda-recipe --output-folder ./conda-packages
    
    - name: Upload to Anaconda.org
      shell: bash -l {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda -t $ANACONDA_API_TOKEN upload conda-packages/noarch/*.tar.bz2 --force