name: JavaScript CI

on:
  push:
    branches: [main]
    paths:
      - 'typescript/**'
      - '.github/workflows/javascript-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'typescript/**'
      - '.github/workflows/javascript-ci.yml'

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: typescript

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: typescript/pnpm-lock.yaml
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run linter
        run: pnpm run lint
        
      - name: Type check
        run: pnpm run type-check
        
      - name: Run tests
        run: pnpm run test
        
      - name: Build
        run: pnpm run build